version: "3.8"
services:
  demodb:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    volumes:
      - local_pgdatademo:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: demopgadmin4_container
    restart: always
    ports:
      - "5088:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: demo@demo.com
      PGADMIN_DEFAULT_PASSWORD: demo
    volumes:
      - pgadmin-datademo:/var/lib/pgadmin

volumes:
  local_pgdatademo:
  pgadmin-datademo:
