[welds]

uri = "postgres://demo:demo@localhost:5432/demo" # Database address
min_connections = 1        # Minimum number of connections in the connection pool, the default value is 1
max_connections = 10       # Maximum number of connections in the connection pool, the default value is 10
acquire_timeout = 30000    # Connection timeout, in milliseconds, default 30s
idle_timeout = 600000      # Connection idle time, in milliseconds, default 10min
connect_timeout = 1800000  # Maximum connection survival time, in milliseconds, default 30min
enable_logging = true      # Print sql log

[weldsmigration]
auto = true

[web]
port = 8080
connect_info = true
graceful = true

[web.openapi]
doc_prefix = "/docs"
info = { title = "autowds api document", version = "0.0.1" }

[web.middlewares]
# Static resource configuration
static = { enable = true, uri = "/apidocs", path = "static/docs", precompressed = true, fallback = "index.html" }
compression = { enable = true }
logger = { enable = true, level = "warn" }
catch_panic = { enable = true }
timeout_request = { enable = true, timeout = 30000 }

# Cross-domain configuration
cors = { enable = true, allow_origins = [
    "*.github.io",
], allow_headers = [
    "Authentication",
], allow_methods = [
    "GET", 
    "POST",
], max_age = 60 }


[mail]
host = "smtp.163.com"                                                      # SMTP mail server address,
port = 465                                                                 # SMTP server port number
secure = true                                                              # Response timeout, in milliseconds
auth = { user = "hff1996723@163.com", password = "${MAIL_AUTH_PASSWORD}" } # Authentication information
stub = true

[email]
from = "demo@demo.fr"


[custom]
user_info_detail = "hello custom config"
